/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadRouteImport } from './routes/actividad'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NuevaVentaRouteImport } from './routes/nueva-venta'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as TicketIndexRouteImport } from './routes/ticket/index'
import { Route as TicketSaleIdRouteImport } from './routes/ticket/$saleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadRoute = ActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaVentaRoute = NuevaVentaRouteImport.update({
  id: '/nueva-venta',
  path: '/nueva-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketSaleIdRoute = TicketSaleIdRouteImport.update({
  id: '/ticket/$saleId',
  path: '/ticket/$saleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/clientes': typeof ClientesRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/ticket/$saleId': typeof TicketSaleIdRoute
  '/ticket/': typeof TicketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/clientes': typeof ClientesRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/ticket/$saleId': typeof TicketSaleIdRoute
  '/ticket': typeof TicketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/clientes': typeof ClientesRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/ticket/$saleId': typeof TicketSaleIdRoute
  '/ticket/': typeof TicketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividad'
    | '/ajustes'
    | '/buscar'
    | '/clientes'
    | '/historial'
    | '/login'
    | '/nueva-venta'
    | '/productos'
    | '/ticket/$saleId'
    | '/ticket/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividad'
    | '/ajustes'
    | '/buscar'
    | '/clientes'
    | '/historial'
    | '/login'
    | '/nueva-venta'
    | '/productos'
    | '/ticket/$saleId'
    | '/ticket'
  id:
    | '__root__'
    | '/'
    | '/actividad'
    | '/ajustes'
    | '/buscar'
    | '/clientes'
    | '/historial'
    | '/login'
    | '/nueva-venta'
    | '/productos'
    | '/ticket/$saleId'
    | '/ticket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadRoute: typeof ActividadRoute
  AjustesRoute: typeof AjustesRoute
  BuscarRoute: typeof BuscarRoute
  ClientesRoute: typeof ClientesRoute
  HistorialRoute: typeof HistorialRoute
  LoginRoute: typeof LoginRoute
  NuevaVentaRoute: typeof NuevaVentaRoute
  ProductosRoute: typeof ProductosRoute
  TicketSaleIdRoute: typeof TicketSaleIdRoute
  TicketIndexRoute: typeof TicketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad': {
      id: '/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof ActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-venta': {
      id: '/nueva-venta'
      path: '/nueva-venta'
      fullPath: '/nueva-venta'
      preLoaderRoute: typeof NuevaVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$saleId': {
      id: '/ticket/$saleId'
      path: '/ticket/$saleId'
      fullPath: '/ticket/$saleId'
      preLoaderRoute: typeof TicketSaleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadRoute: ActividadRoute,
  AjustesRoute: AjustesRoute,
  BuscarRoute: BuscarRoute,
  ClientesRoute: ClientesRoute,
  HistorialRoute: HistorialRoute,
  LoginRoute: LoginRoute,
  NuevaVentaRoute: NuevaVentaRoute,
  ProductosRoute: ProductosRoute,
  TicketSaleIdRoute: TicketSaleIdRoute,
  TicketIndexRoute: TicketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
